[package]
name = "otterbot"
version = "0.1.0"
authors = ["Kyle Gretchev <kgretchev@gmail.com>"]

[dependencies]
hipchat = { git = "https://github.com/devnought/hipchat.git" }
rand = "0.5.4"
serde = "1.0.70"
serde_derive = "1.0.70"
serde_json = "1.0.24"
warp = "0.1.0"
